[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "."
  
  # Default build command
  command = "echo 'No build command needed for static site'"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS for 1 year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JS for 1 year
    Cache-Control = "public, max-age=31536000"

# Redirect rules
[[redirects]]
  from = "/portfolio/*"
  to = "/#portfolio"
  status = 301

[[redirects]]
  from = "/contact/*"
  to = "/#contact"
  status = 301

# Error page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
